[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "build"
  base = "."

[functions]
directory = "netlify/functions"

[deploy]
visibility = "public"
